### ISSUE TITLE
Moving launchpad to the cloud fails: ERROR: argument --ids: expected at least one argument

### ISSUE THREAD

**Issue by segraef** [aztfmod/rover#237]
After deploying launchpad level0 via rover ignite from [contoso-2201](https://github.com/Azure/caf-terraform-landingzones-starter/tree/contoso-2201) it fails with

<img width="512" alt="image" src="https://user-images.githubusercontent.com/19261257/151691047-ddadf732-4c88-416d-a11a-f0c07f6d76e4.png">

```bash
Apply complete! Resources: 146 added, 0 changed, 0 destroyed.

Outputs:

diagnostics = <sensitive>
global_settings = <sensitive>
launchpad_identities = <sensitive>
objects = <sensitive>
tfstates = <sensitive>
Terraform apply return code: 0
@calling get_storage_id
@calling upload_tfstate
Moving launchpad to the cloud
ERROR: argument --ids: expected at least one argument

Examples from AI knowledge base:
az storage account show --ids /subscriptions/{SubID}/resourceGroups/{ResourceGroup}/providers/Microsoft.Storage/storageAccounts/{StorageAccount}
Show properties for a storage account by resource ID.

az storage account show --resource-group MyResourceGroup --name MyStorageAccount
Show properties for a storage account using an account name and resource group.

https://docs.microsoft.com/en-US/cli/azure/storage/account#az_storage_account_show
Read more about the command in reference docs
Error on or near line 142; exiting with status 1
Error on or near line 142; exiting with status 1

@calling clean_up_variables
cleanup variables
clean_up backend_files
vscode@7b5da0201736:/tf/caf/$
```

My details:

`aztfmod/rover:1.1.3-2201.2106`

When I execute the rover command again TF wants me to import everything.

**Comment by arnaudlh** [comment]
This has been taken offline and solved :)

**Comment by nusrath432** [comment]
@arnaudlh What is the solution, please? Do we need to use a different version of Rover?

**Comment by remiwuillemin** [comment]
@arnaudlh, I'm stuck with this one two ! Is it a known issue in a specific Rover version ? Thx in advance !

**Comment by remiwuillemin** [comment]
@nusrath432 
Upgrading rover to last version help. In docker-compose file:
`image: aztfmod/rover:1.1.3-2201.2106`

**Comment by ajaynadakuditi** [comment]
I am facing this problem with the latest rover version:  
`aztfmod/rover:1.5.6-2309.0507`
 
I got the same error with other recent versions as well.  what was the resolution to fix this?

**Comment by h2floh** [comment]
Just if someone finds this issue and has the same problem. 

For me it was that I gave the wrong input ... twice:
- to the  `-level` parameter of the rover script: It should have been `-level level0` and I just put in `-level 0`. 
- to the `-env` parameter of the rover script: It should have been same case as defined in global_settings `-env myenv` but I used upcase `-env MYENV`

Because of that the [storage count search via tags failed](https://github.com/aztfmod/rover/blob/536c930d8f1dac39a174eeead73b4515ed3f8e3f/scripts/tfstate.sh#L649C27-L649C38)/return nothing which triggers the error message in [the next step](https://github.com/aztfmod/rover/blob/536c930d8f1dac39a174eeead73b4515ed3f8e3f/scripts/tfstate.sh#L157).
